### ISSUE TITLE
Default /wiki/syntax page gets corrupted after plugin activation

### ISSUE THREAD

**Issue by Arech** [arapat/markdowku#2]
Hi there!

I've just installed a latest stable DocuWiki installation (DocuWiki-On-Stick for Windows standalone if it matters). After that I installed markdowku plugin via a standard "Extension Manager / Search and Install" feature. Then I navigated to the default `/wiki/syntax` page (rewrite engine is turned on, - but again, I'm not sure if it matters) and saw that the page is not rendered properly. When I disable markdowku plugin in "Extension Manager", the page renders correctly.

Could you please confirm the bug?

Thanks

**Comment by petulf** [comment]
Can confirm same issue, causes rendering issues with pure dokuwiki syntax pages.

**Comment by arapat** [comment]
Hi, this repository is not intended to take over the project but a temporary fix to the PHP 7 incompatibility issue. Please report the issue to the author.
